__default__:
  partition: 'standard' #MODIFY
  group: 'bhurwitz' #MODIFY
  M: 'mattmiller899@email.arizona.edu' #MODIFY
  time: '24:00:00'
  n: '{threads}'
  m: '{resources[mem_mb]}mb'
  o: 'out/{rule}.{wildcards}.out'
  e: 'err/{rule}.{wildcards}.err'
  N: "1"
